### ISSUE TITLE
Update policy js source

### ISSUE THREAD

**Issue by TryTryAgain** [rvedotrc/aws-iam-reference#5]
https://awsiamconsole.s3.amazonaws.com/iam/assets/js/bundles/policies.js to the new policy generator https://awspolicygen.s3.amazonaws.com/js/policies.js in the Makefile will yield over 3500 missing actions. Seems that the old link isn't getting the same attention and the new one contains things moving forward.

**Comment by rrrix** [comment]
@TryTryAgain rad, thank you!

**Comment by TryTryAgain** [comment]
I've actually done a hard fork of this project, rewritten commit messages, added automatic descriptive commit messages, the ci/cd automation to update every 4 hours, and added other features.

It's hosted on GitLab and mirrored to GitHub as well: https://github.com/TryTryAgain/aws-iam-actions-list 

Allows you to regex search commit history pretty easily from the source GitLab project, for example: 
https://gitlab.com/TryTryAgain/aws-iam-actions-list/-/commits/master?search=removed.*ec2

Closing this issue as I think this project is abandoned.
